# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-booklore"
BBFILE_PATTERN_meta-booklore = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-booklore = "6"

LAYERDEPENDS_meta-booklore = "core"
LAYERSERIES_COMPAT_meta-booklore = "kirkstone"
