DISTRO = "booklore"
DISTRO_NAME = "BookLore E-Reader OS"
DISTRO_VERSION = "0.1.0"

VIRTUAL-RUNTIME_init_manager = "sysvinit"
VIRTUAL-RUNTIME_initscripts = "initscripts"

DISTRO_FEATURES = "wifi usbhost usbgadget ipv4 ipv6"
DISTRO_FEATURES:remove = "x11 wayland opengl vulkan pulseaudio bluetooth nfc 3g"

PACKAGE_CLASSES = "package_ipk"

IMAGE_LINGUAS = "en-us"
